version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
  labels:
      - "dependencies"
      - "automerge"
      - "github_actions"
- package-ecosystem: bundler
  directory: "/"
  vendor: true
  schedule:
    interval: daily
  labels:
    - "dependencies"
    - "automerge"
    - "python"
