title: The Better Slots
description: The Better Slots reviews different online casinos and slots so that you always get the best bonus on the best casinos
url: https://TheBetterSlots.com
email: info@TheBetterSlots.com
ver: 0.0.0-local
livereload: true
host: 0.0.0.0
permalink: pretty
sass:
    sass_dir: _sass
    style: compressed
gtm-id: G-629QNE91VX
collections:
  casinos:
    output: true
    sort_by: SortOrder
