title: The Better Slots
description: Description
url: https://www.TheBetterSlots.com
email: info@TheBetterSlots.com
ver: 0.0.0-local
livereload: true
host: 0.0.0.0
permalink: pretty
sass:
    sass_dir: _sass
    style: compressed
# gtm-id: G-BHPW53QJ18
